dist: trusty

language: go

go:
  - "1.10.x"
  - "1.11.x"
  - "1.x"

addons:
  sonarcloud:
    organization: "welldoer-github"
    token:
      secure: "e8dd90ccc383def0adf6926495369421eab149f6" # encrypted value of your token

install: true

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - go test -coverprofile=coverage.out ./... -json > test-report.out
  - sonar-scanner -X
